openapi: 3.0.0
info:
  title: Customer API
  version: 1.0.0

paths:
  /customers:
    get:
      summary: Get all customers
      responses:
        '200':
          description: Success
    post:
      summary: Create a new customer
      requestBody:
        required: true
      responses:
        '201':
          description: Created

  /customers/{id}:
    get:
      summary: Get customer by ID
      responses:
        '200':
          description: Success
    put:
      summary: Update customer
      responses:
        '200':
          description: Updated
    delete:
      summary: Delete customer
      responses:
        '204':
          description: Deleted

  /customers/search:
    get:
      summary: Search customers
      responses:
        '200':
          description: Success
